=== fabiobulgarella/DP2_Assignment_1/xsd/nfvInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:r="http://www.example.org/nfvInfo"
           xmlns="http://www.example.org/nfvInfo"
           targetNamespace="http://www.example.org/nfvInfo"
           elementFormDefault="qualified">
  
  <xs:element name="nfv">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="catalog" />
        <xs:element ref="nffgs" />
        <xs:element ref="hosts" />
        <xs:element ref="connections" />
      </xs:sequence>
    </xs:complexType>
    <xs:key name="vnfKey">
      <xs:selector xpath="r:catalog/r:vnf" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:key name="nffgKey">
      <xs:selector xpath="r:nffgs/r:nffg" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:key name="nodeKey">
      <xs:selector xpath="r:nffgs/r:nffg/r:node" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:key name="hostKey">
      <xs:selector xpath="r:hosts/r:host" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:keyref name="vnfKeyref" refer="vnfKey">
      <xs:selector xpath="r:nffgs/r:nffg/r:node" />
      <xs:field xpath="@vnfRef" />
    </xs:keyref>
    <xs:keyref name="hostKeyref" refer="hostKey">
      <xs:selector xpath="r:nffgs/r:nffg/r:node" />
      <xs:field xpath="@hostRef" />
    </xs:keyref>
    <xs:keyref name="dstNodeKeyref" refer="nodeKey">
      <xs:selector xpath="r:nffgs/r:nffg/r:node/r:link" />
      <xs:field xpath="@dstNode" />
    </xs:keyref>
    <xs:keyref name="nodeKeyref" refer="nodeKey">
      <xs:selector xpath="r:hosts/r:host/r:nodeRef" />
      <xs:field xpath="." />
    </xs:keyref>
    <xs:keyref name="host1Keyref" refer="hostKey">
      <xs:selector xpath="r:connections/r:connection" />
      <xs:field xpath="@host1" />
    </xs:keyref>
    <xs:keyref name="host2Keyref" refer="hostKey">
      <xs:selector xpath="r:connections/r:connection" />
      <xs:field xpath="@host2" />
    </xs:keyref>
  </xs:element>
  
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="vnf" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="vnf">
    <xs:complexType>
      <xs:attribute name="name" type="nameType" use="required" />
      <xs:attribute name="functionalType" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="CACHE" />
            <xs:enumeration value="DPI" />
            <xs:enumeration value="FW" />
            <xs:enumeration value="MAIL_CLIENT" />
            <xs:enumeration value="MAIL_SERVER" />
            <xs:enumeration value="NAT" />
            <xs:enumeration value="SPAM" />
            <xs:enumeration value="VPN" />
            <xs:enumeration value="WEB_CLIENT" />
            <xs:enumeration value="WEB_SERVER" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="reqMemory" type="nonNegativeInt" use="required" />
      <xs:attribute name="reqStorage" type="nonNegativeInt" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="nffgs">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="nffg" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="nffg">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="node" />
      </xs:sequence>
      <xs:attribute name="name" type="nameType" use="required" />
      <xs:attribute name="deployTime" type="xs:dateTime" use="required" />
    </xs:complexType>
    <xs:key name="linkKey">
      <xs:selector xpath="r:node/r:link" />
      <xs:field xpath="@name" />
    </xs:key>
  </xs:element>
  
  <xs:element name="node">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="link" />
      </xs:sequence>
      <xs:attribute name="name" type="nameType" use="required" />
      <xs:attribute name="vnfRef" type="xs:string" use="required" />
      <xs:attribute name="hostRef" type="xs:string" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="link">
    <xs:complexType>
      <xs:attribute name="name" type="nameType" use="required" />
      <xs:attribute name="dstNode" type="xs:string" use="required" />
      <xs:attribute name="minThroughput" type="nonNegativeFloat" />
  	  <xs:attribute name="maxLatency" type="nonNegativeInt" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="hosts">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="host" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="host">
    <xs:complexType>
      <xs:sequence>
  		<xs:element name="nodeRef" type="xs:string" minOccurs="0" maxOccurs="unbounded" /> 
      </xs:sequence>
      <xs:attribute name="name" type="nameType" use="required" />
      <xs:attribute name="maxVnfs" type="nonNegativeInt" use="required" />
  	  <xs:attribute name="memory" type="nonNegativeInt" use="required" />
      <xs:attribute name="storage" type="nonNegativeInt" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="connections">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="connection" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="connection">
    <xs:complexType>
      <xs:attribute name="host1" type="xs:string" use="required" />
      <xs:attribute name="host2" type="xs:string" use="required" />
      <xs:attribute name="throughput" type="nonNegativeFloat" use="required" />
  	  <xs:attribute name="latency" type="nonNegativeInt" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="nameType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z][A-Za-z0-9]*" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="nonNegativeInt">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="nonNegativeFloat">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>
  
  <!-- nffgKey e linkKey possono essere implementati come unique -->
  
</xs:schema>

=== fabiobulgarella/DP2_Assignment_1/xsd/nfvInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<nfv xmlns="http://www.example.org/nfvInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/nfvInfo nfvInfo.xsd">
    <catalog>
        <vnf name="Oe2gjUIjZxT8CWP" functionalType="VPN">
            <reqMemory>1825309561</reqMemory>
            <reqStorage>4215265587</reqStorage>
        </vnf>
        <vnf name="aass667" functionalType="DPI">
            <reqMemory>3470853265</reqMemory>
            <reqStorage>1546716507</reqStorage>
        </vnf>
        <vnf name="aass665" functionalType="MAIL_CLIENT">
            <reqMemory>737506014</reqMemory>
            <reqStorage>4214071586</reqStorage>
        </vnf>
    </catalog>
    <nffgs>
        <nffg name="RL683mQC3RbX" deployTime="1994-02-23T23:55:38.53">
            <node name="Vi" vnfRef="aass667" hostRef="B">
            	<link name="tra4" dstNode="ME" minThroughput="1815826272.79223" maxLatency="316324341" />
            </node>
            <node name="G02B3VY" vnfRef="aass667" hostRef="Bu">
            	<link name="hoh5F" dstNode="ME" minThroughput="1815826272.79223" maxLatency="316324341" />
            	<link name="cab3" dstNode="ME" minThroughput="1815826272.79223" maxLatency="316324341" />
            </node>
        </nffg>
        <nffg name="Tgkkjds878" deployTime="1994-02-23T23:55:38.53">
            <node name="Vi2" vnfRef="aass667" hostRef="Ba">
            	<link name="tra4" dstNode="ME" minThroughput="1815826272.79223" maxLatency="316324341" />
            </node>
            <node name="AG02B3VY" vnfRef="aass667" hostRef="Ba3">
	            <link name="hoh5F" dstNode="ME" minThroughput="1815826272.79223" maxLatency="316324341" />
	            <link name="cab3" dstNode="ME" minThroughput="1815826272.79223" maxLatency="316324341" />
            </node>
        </nffg>
    </nffgs>
    <hosts>
        <host name="B">
            <maxVnfs>1836317562</maxVnfs>
            <memory>1166629081</memory>
            <storage>1496869117</storage>
            <nodeRef>TlT</nodeRef>
            <nodeRef>s</nodeRef>
        </host>
        <host name="Bu">
            <maxVnfs>3008461381</maxVnfs>
            <memory>2853778134</memory>
            <storage>1371499021</storage>
            <nodeRef>C3LW</nodeRef>
        </host>
        <host name="Ba">
            <maxVnfs>1745290025</maxVnfs>
            <memory>4209561870</memory>
            <storage>1144071913</storage>
            <nodeRef>V</nodeRef>
            <nodeRef>rvMzx8</nodeRef>
            <nodeRef>h</nodeRef>
        </host>
        <host name="Ba3">
            <maxVnfs>999499019</maxVnfs>
            <memory>1900398474</memory>
            <storage>2952485073</storage>
            <nodeRef>Tl5K5</nodeRef>
        </host>
        <host name="Ba4">
            <maxVnfs>999499019</maxVnfs>
            <memory>1900398474</memory>
            <storage>2952485073</storage>
            <nodeRef>Tl5K5</nodeRef>
        </host>
    </hosts>
    <connections>
        <connection host1="NQp9g3F" host2="AXDyw7" throughput="612438714.03919" latency="2535065791" />
        <connection host1="NQp9g3F" host2="AXDyw7" throughput="612438714.03919" latency="2535065791" />
        <connection host1="NQp9g3F" host2="AXDyw7" throughput="612438714.03919" latency="2535065791" />
    </connections>
</nfv>
